apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ prefix }}
  namespace: {{ namespace.target }}
  labels: {{ labels }}
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions: {{ app.matchExpressions }}
