apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ prefix }}-git-credentials
  namespace: {{ namespace.channel }}
  labels: {{ labels }}
data:
  {% if helm.user -%}
  user: {{ helm.user | string | b64encode }}
  {% endif -%}
  {% if helm.accessToken -%}
  accessToken: {{ helm.accessToken | string | b64encode }}
  {% endif -%}
