apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: {{ prefix }}-app-subscription
  namespace: {{ namespace.target }}
  labels: {{ labels }}
spec:
  channel: {{ namespace.channel }}/{{ prefix }}-channel
  name: {{ helm.chart.name }}
  packageFilter:
    version: {{ helm.chart.version }}
  packageOverrides:
    - packageAlias: {{ helm.chart.alias }}
      packageName: {{ helm.chart.name }}
  placement:
    placementRef:
      name: {{ prefix }}-placement
      kind: PlacementRule
      group: apps.open-cluster-management.io
